"""
PrimeNet Platform Bootstrap
create_configuration.py

Creates the initial PrimeNet configuration file.

Safe to run multiple times.
Existing configuration files are NEVER overwritten.
"""

from pathlib import Path
from datetime import datetime


PLATFORM_ROOT = Path(r"C:\PrimeNet\Platform")
CONFIG_DIR = PLATFORM_ROOT / "config"
CONFIG_FILE = CONFIG_DIR / "primenet_config.yaml"


CONFIG_TEXT = """# PrimeNet Platform Configuration
# Version: 1.0.0
#
# This file defines the canonical paths and default runtime settings
# for PrimeNet Platform v1.0.
#
# Design principle:
#   No PrimeNet code should hard-code repository or products paths.
#   All paths should be read from this configuration file.

platform:
  name: "PrimeNet Platform"
  version: "1.0.0"
  root: "C:/PrimeNet/Platform"

repository:
  name: "Prime Repository"
  version: "1.0"
  root: "E:/PrimeNet/Repository"
  ranges_dir: "E:/PrimeNet/Repository/ranges"
  index_dir: "E:/PrimeNet/Repository/index"
  manifests_dir: "E:/PrimeNet/Repository/manifests"
  backups_dir: "E:/PrimeNet/Repository/backups"
  scripts_dir: "E:/PrimeNet/Repository/scripts"

products:
  name: "PrimeNet Products"
  version: "1.0"
  root: "E:/PrimeNet/Products"
  results_dir: "E:/PrimeNet/Products/results"
  figures_dir: "E:/PrimeNet/Products/figures"
  atlases_dir: "E:/PrimeNet/Products/atlases"
  reports_dir: "E:/PrimeNet/Products/reports"
  archives_dir: "E:/PrimeNet/Products/archives"
  publications_dir: "E:/PrimeNet/Products/publications"

repository_generation:
  official_range_size: 10000000000
  official_segment_size: 10000000
  official_file_policy: "range-based"
  experimental_range_size: 50000000000
  experimental_segment_size: 50000000
  overwrite_existing: false

runtime:
  log_level: "INFO"
  write_mode: "direct"
  timestamp_format: "iso8601"

validation:
  validate_range_boundaries: true
  validate_sorted_primes: true
  validate_min_max_prime: true
  validate_file_exists: true
  validate_inventory: true

metadata:
  author: "Jinhua Liao"
  ecosystem: "PrimeNet"
  layer_model:
    - "Prime Repository"
    - "PrimeNet Platform"
    - "PrimeNet Products"
    - "Knowledge"
"""


def main() -> None:
    print("=" * 70)
    print("PrimeNet Platform Bootstrap")
    print("Create Configuration")
    print("=" * 70)

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    if CONFIG_FILE.exists():
        print(f"[EXISTS ] {CONFIG_FILE}")
        print("Configuration file already exists. No changes made.")
        return

    timestamp = datetime.now().isoformat(timespec="seconds")

    content = (
        CONFIG_TEXT.rstrip()
        + "\n\n"
        + "# Generated by PrimeNet Bootstrap\n"
        + f"# Timestamp: {timestamp}\n"
    )

    CONFIG_FILE.write_text(content, encoding="utf-8")

    print(f"[CREATED] {CONFIG_FILE}")
    print()
    print("Configuration initialized successfully.")
    print("=" * 70)


if __name__ == "__main__":
    main()