from pathlib import Path
import shutil

THEORY_FIGURES = (
    "fig11_prime_count_comparison",
    "fig12_prime_count_relative_error",
    "fig13_mean_gap_validation",
    "fig13b_mean_gap_ratio",
    "fig14_twin_prime_validation",
    "fig14b_twin_prime_relative_error",
)

def build(outdir, theme_name="primenet_light", stats=None):
    """Install validated theory figures into the active publication tree.

    The figures are generated by the dedicated theory-validation pipeline and
    treated here as verified publication inputs rather than redrawn artifacts.
    """
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    source_dir = Path(r"C:\PrimeNet\paper\output\figures")

    missing = []
    for stem in THEORY_FIGURES:
        for extension in ("png", "svg"):
            source = source_dir / f"{stem}.{extension}"
            target = outdir / source.name
            if not source.is_file():
                missing.append(str(source))
                continue
            shutil.copy2(source, target)

    if missing:
        joined = "\n  ".join(missing)
        raise FileNotFoundError(
            "Theory-validation figure assets are missing:\n  " + joined
        )

    return list(THEORY_FIGURES)
