from .diagram import Diagram
from .layout import vertical_stack,horizontal_stack,grid,center_node
from .shapes import Node

def fig01_evolution(outdir,theme_name='primenet_light'):
 d=Diagram('Evolution of Computational Research','From computation to persistent scientific infrastructure',theme_name=theme_name); nodes=[Node('a','1960s-1980s\nCan we compute?',.08,.62,.22,.12,'neutral'),Node('b','1990s-2010s\nCan we compute faster?',.39,.42,.22,.12,'neutral'),Node('c','2020s-\nHow do we organize,\nverify, preserve,\nshare, and build upon\nwhat we compute?',.70,.18,.24,.18,'foundation')]; d.add_nodes(nodes,8); d.connect('a','b','right','left'); d.connect('b','c','right','left'); d.note('PrimeNet addresses the infrastructure question in computational arithmetic.'); d.save(outdir,'fig01_evolution')
def fig02_architecture(outdir,theme_name='primenet_light'):
 d=Diagram('Overall PrimeNet Architecture','Coordinate, repository, observatory, product, and publication layers',theme_name=theme_name); d.container(.05,.10,.90,.74,'Reference Architecture'); p=d.add_node(Node('p','Prime Space\ncanonical coordinates',.36,.72,.28,.09,'foundation'),8); mids=[Node('r','Persistent\nRepository',.10,.50,.20,.10),Node('o','Observatory\nFramework',.40,.50,.20,.10),Node('m','Metadata\nRegistry',.70,.50,.20,.10)]; d.add_nodes(mids,8); s=d.add_node(Node('s','Observation Sessions',.32,.33,.36,.08,'neutral'),8); pr=d.add_node(Node('pr','Computational Products & Atlases',.27,.19,.46,.08,'foundation'),8); f=d.add_node(Node('f','Future Scientific Investigation',.31,.06,.38,.07,'evidence'),8); [d.connect_nodes(p,m) for m in mids]; [d.connect_nodes(m,s) for m in mids]; d.connect('s','pr'); d.connect('pr','f'); d.save(outdir,'fig02_architecture')
def fig03_prime_space(outdir,theme_name='primenet_light'):
 d=Diagram('Prime Space Coordinate System','Each prime has both numerical value and observational coordinate',theme_name=theme_name); primes=[2,3,5,7,11,13,17]; xs=[.14+i*.12 for i in range(len(primes))]; d.ax.hlines(.46,.08,.92,linewidth=1.4,color=d.theme.muted)
 for i,(x,p) in enumerate(zip(xs,primes),1):
  d.ax.plot([x],[.46],marker='o',color=d.theme.accent,markersize=6); d.ax.text(x,.55,f'p_{i} = {p}',ha='center',fontsize=8,color=d.theme.ink); d.ax.text(x,.34,f'i = {i}',ha='center',fontsize=8,color=d.theme.muted); d.ax.annotate('',xy=(x,.49),xytext=(x,.52),arrowprops=dict(arrowstyle='-|>',color=d.theme.accent,lw=1.0))
 d.add_node(Node('coord','Observation record:  (i, p_i)',.32,.10,.36,.08,'foundation'),9); d.note('The prime index supplies a stable observational coordinate independent of any individual analysis.'); d.save(outdir,'fig03_prime_space')
def fig04_repository(outdir,theme_name='primenet_light'):
 d=Diagram('Layered Repository Architecture','Persistent computational assets separated from services and metadata',7.6,5.8,theme_name); nodes=vertical_stack(['Applications','Observatories','Repository Services','Metadata / Catalogs','Persistent Computational Repository'],.24,.72,.52,.08,.065,'l'); d.add_nodes(nodes); [d.connect_nodes(a,b) for a,b in zip(nodes[:-1],nodes[1:])]; d.note('Layering allows metadata and services to evolve without altering verified computational assets.'); d.save(outdir,'fig04_repository')
def fig05_construction(outdir,theme_name='primenet_light'):
 d=Diagram('Repository Construction Workflow','Deterministic generation followed by independent verification',theme_name=theme_name); nodes=horizontal_stack(['Integer\nInterval','Segment','Prime\nGeneration','Repository\nSegment','Independent\nVerification','Persistent\nRepository'],.04,.47,.13,.11,.025,'step'); d.add_nodes(nodes,7.5); [d.connect_nodes(a,b,'right','left') for a,b in zip(nodes[:-1],nodes[1:])]; d.ax.text(.5,.29,'Verified segments become reusable repository assets.',ha='center',fontsize=9,color=d.theme.muted); d.save(outdir,'fig05_construction')
def fig06_observatory(outdir,theme_name='primenet_light'):
 d=Diagram('PrimeNet Observatory Framework','Reusable scientific instruments operating on persistent repositories',7.6,5.8,theme_name); nodes=vertical_stack(['Persistent Repository','PrimeNet Observatory','Observation Session','Computational Products','Atlas','Future Observatory'],.28,.74,.44,.075,.055,'obs'); nodes[0].kind='foundation'; nodes[-1].kind='evidence'; d.add_nodes(nodes,8); [d.connect_nodes(a,b) for a,b in zip(nodes[:-1],nodes[1:])]; d.note('Observatories produce persistent products that can be reused by future investigations.'); d.save(outdir,'fig06_observatory')
def fig07_software(outdir,theme_name='primenet_light'):
 d=Diagram('PrimeNet Software Architecture','Subsystems with separated responsibilities',theme_name=theme_name); d.add_node(Node('u','User Applications',.36,.74,.28,.08,'neutral'),8); d.add_node(Node('o','Observatory Framework',.32,.58,.36,.08,'foundation'),8); services=[Node('r','Repository\nServices',.08,.36,.22,.10),Node('m','Metadata\nServices',.39,.36,.22,.10),Node('p','Product\nServices',.70,.36,.22,.10)]; d.add_nodes(services,8); d.add_node(Node('store','Persistent Computational Repository',.28,.13,.44,.08,'foundation'),8); d.connect('u','o'); [d.connect_nodes(d.nodes['o'],s) for s in services]; [d.connect_nodes(s,d.nodes['store']) for s in services]; d.save(outdir,'fig07_software')
def fig08_validation(outdir,theme_name='primenet_light',stats=None):
 stats=stats or {}
 d=Diagram('Architectural Validation Evidence','Numbers quantify implementation scale; they do not define the contribution',theme_name=theme_name); labels=[f"Repository interval\n{stats.get('repository_interval','unavailable')}",f"Repository segments\n{stats.get('repository_segments','unavailable')}",f"Verified primes\n{stats.get('verified_prime_numbers','unavailable')}",f"Verification\n{stats.get('repository_verification','unavailable')}",f"Largest stored prime\n{stats.get('largest_stored_prime','unavailable')}"]; nodes=grid(labels,3,.08,.60,.24,.11,.06,.12,'e','evidence'); d.add_nodes(nodes,7.5); f=d.add_node(center_node('Implemented PrimeNet Architecture',.12,.46,.09,'f','foundation'),9); [d.connect_nodes(n,f) for n in nodes]; d.save(outdir,'fig08_validation')
def fig09_growth(outdir,theme_name='primenet_light'):
 d=Diagram('Incremental Repository Growth','Previously verified segments remain stable while new ranges are appended',theme_name=theme_name); nodes=horizontal_stack(['1-10B','10-20B','...','980-990B','990B-1T'],.08,.55,.14,.09,.045,'seg','neutral'); d.add_nodes(nodes,8); repo=d.add_node(Node('repo','Unified Persistent Repository',.30,.22,.40,.09,'foundation'),9); [d.connect_nodes(a,b,'right','left',True) for a,b in zip(nodes[:-1],nodes[1:])]; [d.connect_nodes(n,repo) for n in nodes]; d.save(outdir,'fig09_growth')
def fig10_ecosystem(outdir,theme_name='primenet_light'):
 d=Diagram('PrimeNet Scientific Ecosystem','Infrastructure enables future computational investigations',theme_name=theme_name); nodes=horizontal_stack(['Repository','Observatories','Products','Atlases','Future\nResearchers'],.07,.52,.15,.10,.04,'eco'); nodes[0].kind='foundation'; nodes[-1].kind='evidence'; d.add_nodes(nodes,8); [d.connect_nodes(a,b,'right','left') for a,b in zip(nodes[:-1],nodes[1:])]; base=d.add_node(Node('base','Reusable Foundation for Future Investigation',.25,.20,.50,.09,'foundation'),9); d.connect_nodes(nodes[-1],base); d.note('PrimeNet succeeds if future researchers spend less time rebuilding infrastructure and more time doing science.'); d.save(outdir,'fig10_ecosystem')
FIGURES=[fig01_evolution,fig02_architecture,fig03_prime_space,fig04_repository,fig05_construction,fig06_observatory,fig07_software,fig08_validation,fig09_growth,fig10_ecosystem]
def build_all(outdir,theme_name='primenet_light',stats=None):
 print('Generating figures with Figure Engine 2.3...')
 for i,fn in enumerate(FIGURES,1):
  print(f'  [{i}/{len(FIGURES)}] {fn.__name__}')
  if fn is fig08_validation:
   fn(outdir,theme_name,stats)
  else:
   fn(outdir,theme_name)
