"""Canonical identity for PrimeNet Transition Observatory v1.0."""

PROJECT = "PrimeNet"
OBSERVATORY_ID = "OBS-TRANSITION"
OBSERVATORY_NAME = "Transition Observatory"
OBSERVATORY_CATEGORY = "transition"
VERSION = "1.0.0"
ALGORITHM = "first_order_gap_transition_census"
ALGORITHM_VERSION = "1.0.0"
COORDINATE_SYSTEM = "prime_index"
GAP_OWNERSHIP = "left-owned"
