"""
PrimeNet Platform Bootstrap
create_readme_files.py

Creates standard README.md files for the PrimeNet Platform.

Safe to run multiple times.
Existing README.md files are NEVER overwritten.
"""

from pathlib import Path
from datetime import datetime


PLATFORM_ROOT = Path(r"C:\PrimeNet\Platform")
REPOSITORY_ROOT = Path(r"E:\PrimeNet\Repository")
PRODUCTS_ROOT = Path(r"E:\PrimeNet\Products")


README_TEMPLATES = {

    PLATFORM_ROOT: """
# PrimeNet Platform

## Purpose

PrimeNet Platform is the software foundation of the PrimeNet Ecosystem.

## Responsibilities

- Core framework
- Observatories
- Instruments
- Registry
- Metadata
- Configuration
- Documentation
- Testing

## Relationship

The Platform operates on the Prime Repository and produces PrimeNet Products.
""",

    PLATFORM_ROOT / "bootstrap": """
# Bootstrap

Bootstrap initializes the PrimeNet Platform.

Responsibilities:

- Create directory structure
- Create README files
- Initialize configuration
- Verify installation
""",

    PLATFORM_ROOT / "core": """
# Core

Contains the fundamental infrastructure of PrimeNet.

Responsibilities:

- Base classes
- Utilities
- Shared services
- Common interfaces
""",

    PLATFORM_ROOT / "observatories": """
# Observatories

Scientific workflows built from reusable instruments.

Responsibilities:

- Coordinate instruments
- Produce products
- Generate reports
""",

    PLATFORM_ROOT / "instruments": """
# Instruments

Reusable computational instruments.

Examples:

- Entropy
- Transition
- Spectral Gap
- Mixing Time
""",

    PLATFORM_ROOT / "registry": """
# Registry

Automatic registration of Platform components.

Responsibilities:

- Observatory registration
- Instrument registration
- Discovery
""",

    PLATFORM_ROOT / "metadata": """
# Metadata

Metadata schemas and validation.

Responsibilities:

- Product metadata
- Repository metadata
- Observatory metadata
""",

    PLATFORM_ROOT / "config": """
# Configuration

Configuration files for PrimeNet Platform.

Examples:

- Repository location
- Products location
- Runtime options
""",

    PLATFORM_ROOT / "docs": """
# Documentation

Architecture and technical documentation.

Subdirectories

- architecture
- developer
- specifications
- roadmap
""",

    PLATFORM_ROOT / "tests": """
# Tests

Validation suite for PrimeNet.

Includes

- Unit tests
- Integration tests
- Repository tests
- Performance tests
""",

    PLATFORM_ROOT / "examples": """
# Examples

Minimal working examples demonstrating Platform usage.
""",

    REPOSITORY_ROOT: """
# Prime Repository

The Prime Repository stores reproducible prime datasets.

Responsibilities

- Prime ranges
- Index
- Manifests
- Repository validation

The Repository is independent of the Platform.
""",

    PRODUCTS_ROOT: """
# PrimeNet Products

Scientific outputs generated by PrimeNet.

Examples

- Results
- Figures
- Atlases
- Reports
- Publications
"""
}


def write_readme(folder: Path, text: str):
    readme = folder / "README.md"

    if readme.exists():
        print(f"[EXISTS ] {readme}")
        return False

    content = f"""{text.strip()}

---

Generated by PrimeNet Bootstrap

Timestamp:
{datetime.now().isoformat(timespec='seconds')}
"""

    readme.write_text(content, encoding="utf-8")

    print(f"[CREATED] {readme}")
    return True


def main():

    print("=" * 70)
    print("PrimeNet Platform Bootstrap")
    print("Create README Files")
    print("=" * 70)

    created = 0
    existing = 0

    for folder, text in README_TEMPLATES.items():

        if write_readme(folder, text):
            created += 1
        else:
            existing += 1

    print()
    print("=" * 70)
    print("Summary")
    print("=" * 70)
    print(f"Created : {created}")
    print(f"Existing: {existing}")
    print("=" * 70)


if __name__ == "__main__":
    main()